// Get Music List
export const REQUEST_GET_MUSIC_LIST = 'REQUEST_GET_MUSIC_LIST';
export const REQUEST_GET_MUSIC_LIST_SUCCESS = 'REQUEST_GET_MUSIC_LIST_SUCCESS';
export const REQUEST_GET_MUSIC_LIST_ERROR = 'REQUEST_GET_MUSIC_LIST_ERROR';

// Upload Music
export const REQUEST_UPLOAD_MUSIC = 'REQUEST_UPLOAD_MUSIC';
export const REQUEST_UPLOAD_MUSIC_SUCCESS = 'REQUEST_UPLOAD_MUSIC_SUCCESS';
export const REQUEST_UPLOAD_MUSIC_ERROR = 'REQUEST_UPLOAD_MUSIC_ERROR';

// Control Music
export const PLAY_NEW_AUDIO = 'PLAY_NEW_AUDIO';
export const PLAY_AUDIO = 'PLAY_AUDIO';
export const PAUSE_AUDIO = 'PAUSE_AUDIO';