// Get Music List
export const REQUEST_GET_MUSIC_LIST = 'REQUEST_GET_MUSIC_LIST';
export const REQUEST_GET_MUSIC_LIST_SUCCESS = 'REQUEST_GET_MUSIC_LIST_SUCCESS';
export const REQUEST_GET_MUSIC_LIST_ERROR = 'REQUEST_GET_MUSIC_LIST_ERROR';

// Control Music
export const SET_CURRENT_AUDIO = 'SET_CURRENT_AUDIO';
export const PLAY_AUDIO = 'PLAY_AUDIO';
export const PAUSE_AUDIO = 'PAUSE_AUDIO';