// Get Music List
export const REQUEST_GET_MUSIC_LIST = 'REQUEST_GET_MUSIC_LIST';
export const REQUEST_GET_MUSIC_LIST_SUCCESS = 'REQUEST_GET_MUSIC_LIST_SUCCESS';
export const REQUEST_GET_MUSIC_LIST_ERROR = 'REQUEST_GET_MUSIC_LIST_ERROR';

// Upload Music
export const REQUEST_UPLOAD_MUSIC = 'REQUEST_UPLOAD_MUSIC';
export const REQUEST_UPLOAD_MUSIC_SUCCESS = 'REQUEST_UPLOAD_MUSIC_SUCCESS';
export const REQUEST_UPLOAD_MUSIC_ERROR = 'REQUEST_UPLOAD_MUSIC_ERROR';

// Control Music
export const PLAY_NEW_AUDIO = 'PLAY_NEW_AUDIO';
export const PLAY_AUDIO = 'PLAY_AUDIO';
export const PAUSE_AUDIO = 'PAUSE_AUDIO';

// Auth
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const REQUEST_LOGIN_USER = 'REQUEST_LOGIN_USER';
export const REQUEST_LOGIN_USER_SUCCESS = 'REQUEST_LOGIN_USER_SUCCESS';
export const REQUEST_LOGIN_USER_ERROR = 'REQUEST_LOGIN_USER_ERROR';

export const REQUEST_REGISTER_USER = 'REQUEST_REGISTER_USER';
export const REQUEST_REGISTER_USER_SUCCESS = 'REQUEST_REGISTER_USER_SUCCESS';
export const REQUEST_REGISTER_USER_ERROR = 'REQUEST_REGISTER_USER_ERROR';